### ISSUE TITLE
As a user, I want to be able to view a Gantt-chart of the project timeline, so that I can see the dependencies between tasks and adjust the timeline accordingly.

### ISSUE THREAD

**Issue by Teller501** [ONAV-KEA/ProjectManagement#13]
### _Acceptance Criteria_
- [ ] The Gantt-chart should be in a different view from the task list, found in the menu bar on top of the project page
- [ ] Should update in real-time as task gets completed, deleted or created

**Comment by Teller501** [comment]
Og kan det lade sig gøre, at den kan vise ganttchartet, selvom en task eller subtask ikke har en slut dato? @nicolaiandersson

**Comment by nicolaiandersson** [comment]
Hvis task slutdatoen er null kan den vel sættes til projektets slutdato, og hvis subtask har null slut dato kan den vel sættes til taskens slutdato.. tænker jeg

men jeg sidder stadig og roder med de der dependency arrows/linjer så taskene er grupperet korrekt med subtasksne, prøver at bruge highcharts api nu... @Teller501

**Comment by Teller501** [comment]
@nicolaiandersson true, men hvis nu projektet ik har en slutdato, vi må lige finde ud af det

**Comment by nicolaiandersson** [comment]
Jep, måske skal vi bare kræve at alle projekter har en slutdato så.. fra start

**Comment by nicolaiandersson** [comment]
kan altid rykkes jo @Teller501
