### ISSUE TITLE
As a user, I want to be able to add notes or comments to tasks or the overall project, so that I can provide additional context or information for team members or stakeholders.

### ISSUE THREAD

**Issue by Teller501** [ONAV-KEA/ProjectManagement#14]
### _Acceptance Criteria_
- [x] When clicking on a task, the user can see if there are any notes on the task already, or add a note/comment

**Comment by Teller501** [comment]
Vi skal lige tage stilling til, om man skal kunne have flere comments på en task, for så skal vi have lavet det om til et array af comments

**Comment by nicolaiandersson** [comment]
hmm kan se begge give mening så ved ikke helt

**Comment by VictorHanert** [comment]
Vil mene flere comments ville være bedste løsning - ligesom her på githubben
