### ISSUE TITLE
As a developer i want to be consistent in the design, so all pages, headers and paragraphs looks similar

### ISSUE THREAD

**Issue by Teller501** [ONAV-KEA/ProjectManagement#16]
### _Acceptance Criteria_
- [x] Be consistent in the design, where it will have the same colors, font, sizes etc.
- [x] Every page should make use of Bootstrap Library (CSS)

**Comment by nicolaiandersson** [comment]
![Image](https://user-images.githubusercontent.com/113049347/236781151-015ef631-c425-4c36-a110-b286c7c719f0.png)

@VictorHanert hvis du ikke har set

**Comment by VictorHanert** [comment]
Yep, det burde være til at fixes
