### ISSUE TITLE
As a leader, i want to be able to register employees as project managers or project members, so they can access the interface and projects

### ISSUE THREAD

**Issue by Teller501** [ONAV-KEA/ProjectManagement#3]
###  _Acceptance Criteria_

- [x] Leader have a special login, and when logged in they have access to an exclusive site to register employees
- [x] Employees are given their loginid, password and role
- [x] Employees can then proceed to login

**Comment by VictorHanert** [comment]
@OmarKayed er du i gang med at kigge på den her, ellers har jeg en ide jeg må prøve?

**Comment by OmarKayed** [comment]
@VictorHanert havde lidt en idé til hvordan at jeg skulle gøre det, men er kom med dit input. Det altid et forsøg værd

**Comment by VictorHanert** [comment]
Ok, jeg kigger på det
